version: 2
executorType: docker
jobs:
  build:
    environment:
      # https://circleci.com/docs/1.0/oom/#out-of-memory-errors-in-android-builds
      - JAVA_OPTS: "-Xms512m -Xmx1024m"
      - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    working_directory: ~/app
    docker:
      - image: entria/react-native-android:0.1.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-simpletodo-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-simpletodo-npm
            - v2-simpletodo-android-{{ .Branch }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Relay Compiler
          command: yarn relay
      - run:
          name: Build APK
          command: |
            cp .env.example .env
            cd android
            chmod +x ./gradlew && ./gradlew assembleRelease
      - save_cache:
          key: v1-simpletodo-npm
          paths:
            - node_modules/
      - save_cache:
          key: v1-simpletodo-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - save_cache:
          key: v2-simpletodo-android-{{ .Branch }}
          paths:
            - android/.gradle/
            - /opt/android-sdk-linux
      - store_artifacts:
          path: android/app/build/outputs/apk/
          destination: android
