version: 2
executorType: docker
jobs:
  build:
    environment:
      - TERM: "dumb"
    working_directory: ~/app
    docker:
      - image: webcuisine/gitlab-ci-react-native-android
    steps:
      - checkout
      - run:
          name: Install apt packages
          command: |
            apt-get update
            apt-get install -y python python-dev python-pip python-virtualenv autoconf automake build-essential
      - run:
          name: Install watchman
          command: |
            cd ../
            git clone https://github.com/facebook/watchman.git
            cd watchman
            git checkout v4.7.0  # the latest stable release
            ./autogen.sh
            ./configure
            make
            make install
      - restore_cache:
          keys:
            - v1-simpletodo-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-simpletodo-npm
            - v1-simpletodo-android-{{ .Branch }}-{{ .Environment.CIRCLE_PROJECT_USERNAME }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Relay Compiler
          command: yarn relay
      - run:
          name: Build APK
          command: |
            cp .env.example .env
            cd android
            chmod +x ./gradlew && ./gradlew assembleRelease
      - save_cache:
          key: v1-simpletodo-npm
          paths:
            - node_modules/
      - save_cache:
          key: v1-simpletodo-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - save_cache:
          key: v1-simpletodo-android-{{ .Branch }}-{{ .Environment.CIRCLE_PROJECT_USERNAME }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}
          paths:
            - android/.gradle/
      - store_artifacts:
          path: android/app/build/outputs/apk/
          destination: android
