version: 2
executorType: docker
jobs:
  build:
    environment:
      - NODE_ENV: "production"
      - TERM: "dumb"
    working_directory: ~/app
    docker:
      - image: webcuisine/gitlab-ci-react-native-android
      - image: python:2.7.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-simpletodo-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-simpletodo-npm
            - v1-simpletodo-android-{{ .Branch }}-{{ .Environment.CIRCLE_PROJECT_USERNAME }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build APK
          command: |
            cp .env.example .env
            cd android
            chmod +x ./gradlew && ./gradlew assembleRelease
      - save_cache:
          key: v1-simpletodo-npm
          paths:
            - node_modules/
      - save_cache:
          key: v1-simpletodo-npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - save_cache:
          key: v1-simpletodo-android-{{ .Branch }}-{{ .Environment.CIRCLE_PROJECT_USERNAME }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}
          paths:
            - android/.gradle/
      - store_artifacts:
          path: android/app/build/outputs/apk/
          destination: android
