export default {

    'INVALID_USER'     : 'INVALID_USER',
    'INVALID_PASSWORD' : 'INVALID_PASSWORD',
    'EMAIL_ALREADY_IN_USE' : 'EMAIL_ALREADY_IN_USE',
    'INVALID_EMAIL_PASSWORD' : 'INVALID_EMAIL_PASSWORD',
}
